//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgecam_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Consultas_Ec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consultas_Ec() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edgecam_Manager.Consultas_Ec", typeof(Consultas_Ec).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select JOB_CAM_FILE, JOB_CAD_FILE from TS_JOB where JOB_JOB_DESCRIPTION = @JOB.
        /// </summary>
        internal static string BUSCA_ARQUIVO_PPF_ORDEM {
            get {
                return ResourceManager.GetString("BUSCA_ARQUIVO_PPF_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	JBP_JOB_IMAGE_ID, 
        ///		JBP_IMAGE_DESC as &apos;Descrição da imagem&apos;, 
        ///		JBP_IMAGE_BLOB 
        ///from TS_JOB_IMAGES 
        ///where JBP_JOB_ID=@JOBID.
        /// </summary>
        internal static string BUSCA_IMAGENS_POR_JOBID {
            get {
                return ResourceManager.GetString("BUSCA_IMAGENS_POR_JOBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	ISNULL(COUNT(SKA_TL3.TL_TOOL_DESCRIPTION), 0) AS TL_QTDE_USED
        ///FROM TS_JOB AS SKA_TL1
        ///	INNER JOIN TS_MOUNTING  AS SKA_TL2
        ///		ON SKA_TL1.JOB_JOB_DESCRIPTION = SKA_TL2.MNT_JOB_DESC 
        ///	INNER JOIN TS_TOOL AS SKA_TL3
        ///		ON SKA_TL2.MNT_TOOL_ID = SKA_TL3.TL_TOOL_ID
        ///	INNER JOIN TS_JOB_INSTRUCTION AS SKA_TL4
        ///		ON SKA_TL4.JBI_JOB_DESC=SKA_TL2.MNT_JOB_DESC
        ///		AND SKA_TL4.JBI_TURRET_POSITION = SKA_TL2.MNT_TURRET_POSITION
        ///WHERE SKA_TL3.TL_TOOL_ID = @TOOLID
        ///GROUP BY SKA_TL3.TL_TOOL_ID , SKA_TL3.TL_TOOL_DESCRIPT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BUSCA_QTDE_USED_TOOL {
            get {
                return ResourceManager.GetString("BUSCA_QTDE_USED_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TS_JOB (JOB_JOB_DESCRIPTION, JOB_COMMENT, JOB_FAMILY, JOB_LOCATION, JOB_CUSTOMER, JOB_PROGRAMMER,
        ///					JOB_MATERIAL_DESC, JOB_JOB_STATUS_ID, JOB_CAD_FILE, JOB_PREDEFINED_TOOLING,
        ///					JOB_REVISION, JOB_NOTES_SUBJECT, JOB_NOTES_FILE, JOB_NOTES, JOB_FIXTURE_NOTES_SUBJECT,
        ///					JOB_FIXTURE_NOTES_FILE, JOB_FIXTURE_NOTES, JOB_STOCK_NOTES_SUBJECT, JOB_STOCK_NOTES_FILE, JOB_STOCK_NOTES, 
        ///					JOB_VISIBILITY, JOB_TURRET_WARNING, JOB_CREATED, JOB_MODIFIED)
        ///			VALUES (@DESC, @COMMENT, @FAMILY, @LOCAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CADASTRA_NOVO_TRABALHO {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_TRABALHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update TS_JOB set JOB_JOB_STATUS_ID = 5 WHERE JOB_JOB_DESCRIPTION = @JOBNAME.
        /// </summary>
        internal static string CANCELA_TRABALHO {
            get {
                return ResourceManager.GetString("CANCELA_TRABALHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	T1.STOCK_STOCK_ID AS &apos;Id&apos;,
        ///		T1.STOCK_TYPE_ID AS &apos;Tipo_db&apos;,
        ///		T1.STOCK_REFID AS &apos;Nome&apos;,
        ///		(
        ///			SELECT MAT_MATERIAL_DESCRIPTION 
        ///			FROM TS_MATERIAL
        ///			WHERE MAT_MATERIAL_ID = T1.STOCK_MATERIAL_ID
        ///		) AS &apos;Material&apos;,
        ///		T1.STOCK_LENGTH AS &apos;Comprimento&apos;
        ///FROM TS_STOCKS AS T1
        ///WHERE T1.STOCK_REFID != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_BRUTOS {
            get {
                return ResourceManager.GetString("CONSULTA_BRUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	T1.JOB_JOB_DESCRIPTION,
        ///		ISNULL(T1.JOB_NC_FILE, &apos;CNC não localizado&apos;) AS JOB_NC_FILE,
        ///		T1.JOB_MODIFIED
        ///FROM TS_JOB AS T1
        ///WHERE T1.JOB_JOB_DESCRIPTION&lt;&gt;&apos;&lt;All Kit&gt;&apos;.
        /// </summary>
        internal static string CONSULTA_CNCS {
            get {
                return ResourceManager.GetString("CONSULTA_CNCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct JOB_FAMILY from TS_JOB where JOB_FAMILY IS NOT NULL.
        /// </summary>
        internal static string CONSULTA_FAMILIAS {
            get {
                return ResourceManager.GetString("CONSULTA_FAMILIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Consulta as instruções do trabalho referênciado
        ///select	JBI_INSTRUCTION as &apos;Ordem&apos;,
        ///		JBI_INSTRUCTION_TYPE_ID as &apos;Tipo_Instru_Db&apos;,
        ///		JBI_INSTRUCTION_DESC as &apos;Descrição&apos;,
        ///		JBI_SPEED as &apos;Velocidade (RPM)&apos;,
        ///		JBI_FEED as &apos;Avanço lateral&apos;,
        ///		JBI_PLUNGE as &apos;Avanço vertical&apos;,
        ///		JBI_TIME as &apos;Tempo do processo&apos;
        ///from TS_JOB_INSTRUCTION
        ///where JBI_INSTRUCTION_TYPE_ID IN (0, 1, 2, 3, 4, 5)
        ///and JBI_JOB_DESC = @JOBNAME.
        /// </summary>
        internal static string CONSULTA_INSTRUCOES_TRABALHO {
            get {
                return ResourceManager.GetString("CONSULTA_INSTRUCOES_TRABALHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select MAT_MATERIAL_ID, MAT_MATERIAL_DESCRIPTION, MAT_COMMENT from TS_MATERIAL.
        /// </summary>
        internal static string CONSULTA_MATERIAIS {
            get {
                return ResourceManager.GetString("CONSULTA_MATERIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	T3.TL_TOOL_DESCRIPTION AS &apos;Nome da ferramenta&apos;,
        ///		T4.JBI_TURRET_POSITION AS &apos;Posição na torre&apos;,
        ///		SUBSTRING(T4.JBI_TIME, 11, 8) AS &apos;Tempo total de usinagem&apos;,
        ///		(
        ///			SELECT TMP1.JBI_INSTRUCTION_DESC
        ///			FROM TS_JOB_INSTRUCTION AS TMP1 WITH (NOLOCK)
        ///			WHERE TMP1.JBI_JOB_INSTRUCTION_ID = T4.JBI_JOB_INSTRUCTION_ID + 1
        ///		) AS &apos;Estratégia&apos;,
        ///		T4.JBI_INSTRUCTION AS &apos;Ordem de execução da estratégia&apos;
        ///FROM TS_JOB AS T1
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T1.JOB_JOB_DESCRIPTION = T2.MNT_JOB_DESC 
        ///	IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_TEMPOS_FERRAMENTA_POR_JOB {
            get {
                return ResourceManager.GetString("CONSULTA_TEMPOS_FERRAMENTA_POR_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	DISTINCT T1.TL_TOOL_DESCRIPTION AS &apos;Descrição&apos;,
        ///		T1.TL_TOOL_ID AS &apos;id&apos;,
        ///		T1.TL_TOOL_TYPE_ADDITIVE_ID AS &apos;Tipo_Db&apos;,
        ///		T1.TL_UNITS_ID AS &apos;Unidade_Db&apos;,
        ///		T1.TL_DIAMETER AS &apos;Diâmetro&apos;,
        ///		T1.TL_VISIBILITY AS &apos;Visibilidade&apos;
        ///FROM TS_TOOL AS T1 WITH (NOLOCK)
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T2.MNT_TOOL_ID=T1.TL_TOOL_ID.
        /// </summary>
        internal static string CONSULTA_TOOLS_ADDITIVE {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_ADDITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	T1 - TS_JOB				(DADOS GERAIS DO TRABALHO)
        ///	T2 - TS_MOUNTING		(MONTAGENS DE FERRAMENTAS)
        ///	T3 - TS_TOOL			(FERRAMENTAS)
        ///	T4 - TS_JOB_INSTRUCTION (INSTRUÇÕES
        ///*/
        ///SELECT	T2.MNT_TURRET_POSITION AS &apos;Posição&apos;,
        ///		T3.TL_TOOL_DESCRIPTION AS &apos;Nome da ferramenta&apos;,
        ///		--Ferramentas de fresamento
        ///		ISNULL(T3.TL_TOOL_TYPE_MILL_ID, -1) AS TL_TOOL_TYPE_MILL_ID,
        ///		ISNULL(T3.TL_DIAMETER, 0)  AS &apos;Diâmetro&apos;,
        ///		--Ferramentas de torneamento
        ///		ISNULL(T3.TL_TOOL_TYPE_TURN_ID, -1) AS TL_TOOL_TYPE_TURN_ID,
        ///		ISNULL(T3. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_TOOLS_BY_JOB {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_BY_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	DISTINCT T1.TL_TOOL_DESCRIPTION AS &apos;Descrição&apos;,
        ///		T1.TL_TOOL_ID AS &apos;id&apos;,
        ///		T1.TL_TOOL_TYPE_HOLE_ID AS &apos;Tipo_Db&apos;,
        ///		T1.TL_TEETH AS &apos;Dentes&apos;,
        ///		T1.TL_UNITS_ID AS &apos;Unidade_Db&apos;,
        ///		ISNULL(T1.TL_HAND_OF_THREAD_ID, 0) AS &apos;LadoFerramenta_Db&apos;,
        ///		ISNULL(T1.TL_THREAD, 0) AS &apos;Passo&apos;,--Thread Pitch / TPI
        ///		ISNULL(T1.TL_THREAD_STORED_ID, 2) AS &apos;TipoRosca_Db&apos;,--0 - TPI (The number of threads per inch.) / 1 - Pitch / 2- N/A
        ///		T1.TL_DIAMETER AS &apos;Diâmetro&apos;,
        ///		T1.TL_VISIBILITY AS &apos;Visibilidade&apos;,
        ///		T2.MNT_ROUG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_TOOLS_HOLE {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_HOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	TS_MOUNTING.MNT_TURRET_POSITION,
        ///		CONCAT(&apos;T&apos;, ISNULL(TS_MOUNTING.MNT_TURRET_POSITION, 0), &apos; - &apos;, TS_TOOL.TL_TOOL_DESCRIPTION) as TL_TOOL_DESCRIPTION,
        ///		ISNULL(TS_TOOL.TL_TOOL_TYPE_MILL_ID, -1) AS TL_TOOL_TYPE_MILL_ID,
        ///		ISNULL(TS_TOOL.TL_TOOL_TYPE_TURN_ID, -1) AS TL_TOOL_TYPE_TURN_ID,
        ///		ISNULL(TS_TOOL.TL_TOOL_TYPE_HOLE_ID, -1) AS TL_TOOL_TYPE_HOLE_ID
        ///FROM TS_JOB 
        ///	INNER JOIN TS_MOUNTING 
        ///		ON TS_JOB.JOB_JOB_DESCRIPTION = TS_MOUNTING.MNT_JOB_DESC 
        ///	INNER JOIN TS_TOOL 
        ///		ON TS_MOUNTING.MNT_TO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_TOOLS_INSTRUCOES {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_INSTRUCOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	DISTINCT T1.TL_TOOL_DESCRIPTION AS &apos;Descrição&apos;,
        ///		T1.TL_TOOL_ID AS &apos;id&apos;,
        ///		T1.TL_TOOL_TYPE_MILL_ID AS &apos;Tipo_Db&apos;,
        ///		T1.TL_UNITS_ID AS &apos;Unidade_Db&apos;,
        ///		T1.TL_DIAMETER AS &apos;Diâmetro&apos;,
        ///		T1.TL_VISIBILITY AS &apos;Visibilidade&apos;,
        ///		T2.MNT_ROUGHING_TOOL AS &apos;Para desbaste&apos;,
        ///		T2.MNT_FINISHING_TOOL AS &apos;Para acabamento&apos;
        ///FROM TS_TOOL AS T1 WITH(NOLOCK)
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T2.MNT_TOOL_ID=T1.TL_TOOL_ID.
        /// </summary>
        internal static string CONSULTA_TOOLS_MILL {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_MILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	DISTINCT T1.TL_TOOL_DESCRIPTION AS &apos;Descrição&apos;,
        ///		T1.TL_TOOL_ID AS &apos;id&apos;,
        ///		T1.TL_TOOL_TYPE_PROBE_ID AS &apos;Tipo_Db&apos;,
        ///		T1.TL_UNITS_ID AS &apos;Unidade_Db&apos;,
        ///		T1.TL_DIAMETER AS &apos;Diâmetro&apos;,
        ///		T1.TL_VISIBILITY AS &apos;Visibilidade&apos;,
        ///		T2.MNT_GAUGE_POINT_ID AS &apos;PontoDefasagem_Db&apos;--0 Primário / 1 Secundário (no meio)
        ///FROM TS_TOOL AS T1 WITH (NOLOCK)
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T2.MNT_TOOL_ID=T1.TL_TOOL_ID.
        /// </summary>
        internal static string CONSULTA_TOOLS_PROBE {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_PROBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	DISTINCT T1.TL_TOOL_DESCRIPTION AS &apos;Descrição&apos;,
        ///		T1.TL_TOOL_ID AS &apos;id&apos;,
        ///		T1.TL_TOOL_TYPE_TURN_ID AS &apos;Tipo_Db&apos;,
        ///		ISNULL(T1.TL_SYMBOL_ID, 0) AS &apos;Símbolo_Db&apos;,
        ///		T1.TL_UNITS_ID AS &apos;Unidade_Db&apos;,
        ///		ISNULL(T1.TL_HAND_OF_TOOL_ID, 0) AS &apos;LadoFerramenta_Db&apos;,
        ///		T1.TL_VISIBILITY AS &apos;Visibilidade&apos;,
        ///		T2.MNT_ROUGHING_TOOL AS &apos;Para desbaste&apos;,
        ///		T2.MNT_FINISHING_TOOL AS &apos;Para acabamento&apos;
        ///FROM TS_TOOL AS T1 WITH(NOLOCK)
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T2.MNT_TOOL_ID=T1.TL_TOOL_ID.
        /// </summary>
        internal static string CONSULTA_TOOLS_TURN {
            get {
                return ResourceManager.GetString("CONSULTA_TOOLS_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	JOB_JOB_ID as &apos;id&apos;,
        ///		JOB_JOB_DESCRIPTION as &apos;Nome do trabalho&apos;,
        ///		JOB_COMMENT as &apos;Comentário&apos;,
        ///		JOB_FAMILY as &apos;Familía&apos;,
        ///		JOB_SEQUENCE as &apos;Sequência&apos;,
        ///		JOB_LOCATION as &apos;Máquina&apos;,
        ///		JOB_CUSTOMER as &apos;Cliente&apos;,
        ///		JOB_PROGRAMMER as &apos;Programador&apos;,
        ///		JOB_MATERIAL_DESC as &apos;Material&apos;,
        ///		JOB_JOB_STATUS_ID as &apos;Status_Db&apos;,
        ///		JOB_CAM_FILE as &apos;Arquivo PPF&apos;,
        ///		JOB_CAD_FILE as &apos;Arquivo CAD&apos;,
        ///		JOB_NC_FILE as &apos;Arquivo CNC&apos;,
        ///		JOB_PREDEFINED_TOOLING as &apos;Pré-carga de ferramentas&apos;,
        ///		JOB_REVISION as &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_TRABALHOS {
            get {
                return ResourceManager.GetString("CONSULTA_TRABALHOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 T1.JOB_JOB_ID from TS_JOB AS T1 order by T1.JOB_JOB_ID desc.
        /// </summary>
        internal static string CONSULTA_ULTIMO_JOB_ID {
            get {
                return ResourceManager.GetString("CONSULTA_ULTIMO_JOB_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	T1.JOB_JOB_DESCRIPTION AS &apos;Nome do trabalho&apos;, 
        ///		T1.JOB_SEQUENCE as &apos;Sequência&apos;,
        ///		COUNT(T3.TL_TOOL_ID) AS &apos;Quantidade de vezes utilizada no trabalho&apos;
        ///FROM TS_JOB AS T1
        ///	INNER JOIN TS_MOUNTING AS T2
        ///		ON T1.JOB_JOB_DESCRIPTION = T2.MNT_JOB_DESC 
        ///	INNER JOIN TS_TOOL AS T3
        ///		ON T2.MNT_TOOL_ID = T3.TL_TOOL_ID
        ///	INNER JOIN TS_JOB_INSTRUCTION AS T4
        ///		ON T4.JBI_JOB_DESC=T2.MNT_JOB_DESC
        ///		AND T4.JBI_TURRET_POSITION = T2.MNT_TURRET_POSITION
        ///WHERE	T1.JOB_JOB_DESCRIPTION &lt;&gt; &apos;&lt;All Kit&gt;&apos; AND
        ///		--T3.TL_T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_USABILIDADE_TOOLS_IN_JOBS {
            get {
                return ResourceManager.GetString("CONSULTA_USABILIDADE_TOOLS_IN_JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from TS_JOB_IMAGES where JBP_JOB_IMAGE_ID=@IDIMG.
        /// </summary>
        internal static string DELETA_IMAGEM_BANCO_POR_ID {
            get {
                return ResourceManager.GetString("DELETA_IMAGEM_BANCO_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from TS_JOB where JOB_JOB_ID = @JOBID
        ///delete from TS_JOB_DESC where JBD_JOB_DESC = @JOBNAME
        ///delete from TS_JOB_IMAGES where JBP_JOB_ID = @JOBID
        ///delete from TS_JOB_INSTRUCTION where JBI_JOB_DESC = @JOBID.
        /// </summary>
        internal static string DELETA_TRABALHOS_E_VINCULOS {
            get {
                return ResourceManager.GetString("DELETA_TRABALHOS_E_VINCULOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into TS_JOB_IMAGES (JBP_JOB_ID, JBP_IMAGE_DESC, JBP_IMAGE_TOOLTIP,
        ///						   JBP_IMAGE_NAME, JBP_IMAGE_URL, JBP_IMAGE_ORDER,
        ///						   JBP_CREATED, JBP_MODIFIED, JBP_IMAGE_BLOB)
        ///				   values (@JOBID, @NOMEIMG, @NOMEIMG,
        ///						   @NOMEIMG, @DIRIMG, @IMGORDER,
        ///						   @DTCREATE, @DTMODIFY, CONVERT(varbinary(max),@IMGBUFFER)).
        /// </summary>
        internal static string INSERE_MAGEM_EDGECAM {
            get {
                return ResourceManager.GetString("INSERE_MAGEM_EDGECAM", resourceCulture);
            }
        }
    }
}
