//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgecam_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Consultas_EcMgr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consultas_EcMgr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edgecam_Manager.Consultas_EcMgr", typeof(Consultas_EcMgr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HistoricoModOrcamentos (IdOrcamento, Versao, InfoModificacoes, UsuarioResp, DtModificacao)
        ///			VALUES (@ID, @VERSAO, @INFO, @USR, GETDATE());.
        /// </summary>
        internal static string ADICIONA_HISTORICO_ORCAMENTOS {
            get {
                return ResourceManager.GetString("ADICIONA_HISTORICO_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into HistoricoModOrdens (IdOrdem, InfoModificacoes, UsuarioResp, DtModificacao)
        ///values (@IDORDEM, @INFO, @USR, GETDATE());.
        /// </summary>
        internal static string ADICIONA_HISTORICO_ORDENS {
            get {
                return ResourceManager.GetString("ADICIONA_HISTORICO_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into HistoricoModTrabalhos (IdJob, InfoModificacoes, UsuarioResp, DtModificacao)
        ///values (@IDJOB, @INFO, @USR, GETDATE());.
        /// </summary>
        internal static string ADICIONA_HISTORICO_TRABALHOS {
            get {
                return ResourceManager.GetString("ADICIONA_HISTORICO_TRABALHOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO MarkupImpostos ([IdImposto],[NomeImposto],[ValorImposto],[DtCriacao],[UsuarioCriacao])
        ///					VALUES (@ID, @NOME, @VALOR, GETDATE(), @USR);.
        /// </summary>
        internal static string ADICIONA_IMPOSTOS_MARKUP {
            get {
                return ResourceManager.GetString("ADICIONA_IMPOSTOS_MARKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensExportar SET Ativo = 1 where id = @ID.
        /// </summary>
        internal static string ATIVA_CAMPO_EXPORTACAO {
            get {
                return ResourceManager.GetString("ATIVA_CAMPO_EXPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensImportar SET Ativo = 1 where id = @ID.
        /// </summary>
        internal static string ATIVA_CAMPO_IMPORTACAO {
            get {
                return ResourceManager.GetString("ATIVA_CAMPO_IMPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Usuarios set Email = @USREMAIL, Cargo = @POSITION, Gestor = @BOSS, UnidadeOrg = @UNI where id = @ID.
        /// </summary>
        internal static string ATUALIZA_CADASTRO_USUARIO {
            get {
                return ResourceManager.GetString("ATUALIZA_CADASTRO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensExportar SET NomeImportar = @NOME_XML, AceitarValoresVazios = @ACEITAR_NULL, ValorPadrao = @DEFAULT, DtUltimaMod = @DTM WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_CAMPO_EXPORTACAO {
            get {
                return ResourceManager.GetString("ATUALIZA_CAMPO_EXPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensImportar SET NomeImportar = @NOME_XML, AceitarValoresVazios = @ACEITAR_NULL, ValorPadrao = @DEFAULT, DtUltimaMod = @DTM WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_CAMPO_IMPORTACAO {
            get {
                return ResourceManager.GetString("ATUALIZA_CAMPO_IMPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE @TABELA ALTER COLUMN @COLUNA @TIPO;.
        /// </summary>
        internal static string ATUALIZA_COLUNA {
            get {
                return ResourceManager.GetString("ATUALIZA_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigNotificacoes SET	MostrarNotificacoes = @MOSTRAR,
        ///								Tempo = @TEMPO,
        ///								TempoAnimacao = @TEMPO_ANIMACAO,
        ///								NotifyNovasOrdens = @ORDENS,
        ///								NotifyNovasOrdensErro = @ORDENS_ERRO,
        ///								NotifyNovosOrçamentos = @ORCAMENTOS,
        ///								NotifyInventario = @INVENTARIO,
        ///								NotifyEstoqueMinimo = @ESTOQUE,
        ///								NotifyOrdensAtrasadas = @ORDENS_ATRASADAS,
        ///								DtUltimaMod = @DATA_ULTMOD
        ///WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_CONFIGURACAO_NOTIFICACOES {
            get {
                return ResourceManager.GetString("ATUALIZA_CONFIGURACAO_NOTIFICACOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update InventarioFerramentas set EstadoEstoque = @ESTADO where id = @ID;.
        /// </summary>
        internal static string ATUALIZA_ESTADO_ESTOQUE_TOOL {
            get {
                return ResourceManager.GetString("ATUALIZA_ESTADO_ESTOQUE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Ordens SET Estado = 3 WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_ESTADO_ORDEM {
            get {
                return ResourceManager.GetString("ATUALIZA_ESTADO_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Usuarios set Imagem = CONVERT(varbinary(max),@IMG) where id = @ID.
        /// </summary>
        internal static string ATUALIZA_FOTO_USUARIO {
            get {
                return ResourceManager.GetString("ATUALIZA_FOTO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Ordens SET IsOpened = 0, UsuarioTrabalhando = &apos;&apos;, TempoGastoPrg = @TMP WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_ORDEM_USUARIO_NAO_ESTA_TRABALHANDO {
            get {
                return ResourceManager.GetString("ATUALIZA_ORDEM_USUARIO_NAO_ESTA_TRABALHANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Ordens SET IsOpened = 1, UsuarioTrabalhando = @USER, Estado = 2 WHERE id = @ID.
        /// </summary>
        internal static string ATUALIZA_ORDEM_USUARIO_TRABALHANDO {
            get {
                return ResourceManager.GetString("ATUALIZA_ORDEM_USUARIO_TRABALHANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Ordens set Estado = 7 where id in ({0}).
        /// </summary>
        internal static string ATUALIZA_ORDENS_COMO_ATRASADAS {
            get {
                return ResourceManager.GetString("ATUALIZA_ORDENS_COMO_ATRASADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @QTDE_ATUAL AS INTEGER = (SELECT QuantidadeEstoque FROM InventarioFerramentas WHERE IdTool = @ID);
        ///
        ///UPDATE InventarioFerramentas set QuantidadeEstoque = @QTDE_ATUAL + @NEWQTDE where IdTool = @ID;
        ///
        ///SELECT QuantidadeEstoque from InventarioFerramentas WHERE IdTool = @ID.
        /// </summary>
        internal static string ATUALIZA_QTDE_ESTOQUE_TOOL {
            get {
                return ResourceManager.GetString("ATUALIZA_QTDE_ESTOQUE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update ConfigReferenciasAutomaticas 
        ///set Tabela=@TBL, 
        ///Coluna=@CLM, 
        ///Prefixo=@PRE, 
        ///Incremento=@INC, 
        ///ValorInicial=@VI, 
        ///ValorFinal=@VF, 
        ///ContadorAtual=@VA, 
        ///InserirZeros=@INSZEROS, 
        ///ZerosAesquerda=@ESQ, 
        ///ZerosAdireita=@DIR, 
        ///NumZerosInserir=@NUMZEROS, 
        ///UltDataMod=@DT
        ///where Id=@ID.
        /// </summary>
        internal static string ATUALIZA_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("ATUALIZA_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Usuarios SET Senha = @PASS where Login = @USER.
        /// </summary>
        internal static string ATUALIZA_SENHA_USUARIO {
            get {
                return ResourceManager.GetString("ATUALIZA_SENHA_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Tarefas set Assunto = @ASSUNTO, Instrucoes = @INSTRU, TipoTarefa = @TIPO, PrioridadeTarefa = @PRIORIDADE, DtInicio = @DTINICIO, DtLimite = @DTFIM,
        ///				   DtUltimaMod = @DTULTMOD, UsuarioUltimaMod = @USRULTMOD where id = @ID.
        /// </summary>
        internal static string ATUALIZA_TAREFA {
            get {
                return ResourceManager.GetString("ATUALIZA_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update ConfigReferenciasAutomaticas set ContadorAtual = @NEWVALUE where Tabela = @TBL and Coluna = @CLM.
        /// </summary>
        internal static string ATUALIZA_VALOR_CONTADOR_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("ATUALIZA_VALOR_CONTADOR_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	ContadorAtual + Incremento as &apos;ContadorAtual&apos;,
        ///		Prefixo,
        ///		InserirZeros,
        ///		ZerosAesquerda,
        ///		ZerosAdireita,
        ///		NumZerosInserir
        ///from ConfigReferenciasAutomaticas 
        ///where Tabela = @TBL and Coluna = @CLM.
        /// </summary>
        internal static string BUSCA_NOVO_VALOR_CONTADOR_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("BUSCA_NOVO_VALOR_CONTADOR_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Clientes (NomeEmpresa, Setor, Endereco, Cep, Cidade, Estado, Pais, CNPJ, NomeInterno, Telefone, Email, 
        ///					  IsCliente, IsFornecedor, IsDistribuidor, UsuarioCriacao, DtCriacao, UsuarioUltimaMod, DtUltimaMod)
        ///			  VALUES (@NOME, @S, @E, @C, @CIDADE, @UF, @PAIS, @CNPJ, @NI, @T, @EMAIL,
        ///					  @ISCLIENTE, @ISFORNECEDOR, @ISDISTRIBUIDOR, @USR, GETDATE(), @USR, GETDATE());.
        /// </summary>
        internal static string CADASTRA_CLIENTE {
            get {
                return ResourceManager.GetString("CADASTRA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ContatosClientes (Nome, SobreNome, Setor, Email, TelefoneComercial, TelefoneCelular, Cliente, 
        ///							  Cidade, Estado, Pais, Ativo, DtCriacao, UsuarioCriacao, DtUltimaMod, UsuarioUltMod)
        ///					  VALUES (@N, @S, @SETOR, @EMAIL, @TELCOM, @TELCEL, @CLT,
        ///							  @CIDADE, @ESTADO, @PAIS, 1, GETDATE(), @USR, GETDATE(), @USR);.
        /// </summary>
        internal static string CADASTRA_CONTATO_CLIENTE {
            get {
                return ResourceManager.GetString("CADASTRA_CONTATO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO OrcamentosDetaCustos (IdOrcamento, Descricao, Tipo, Valor, Versao, DtCriacao, UsuarioCriacao)
        ///			VALUES (@ID, @DESC, @TIPO, @VALOR, @VER, GETDATE(), @USR).
        /// </summary>
        internal static string CADASTRA_CUSTOS_DETALHADOS_ORCAMENTOS {
            get {
                return ResourceManager.GetString("CADASTRA_CUSTOS_DETALHADOS_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO InventarioFerramentas ([IdTool],[DescricaoTool],[TipoTool],[SubTipoTool],[UnidadeMedida],[TipoGestaoVidaUtil],[TempoVidaUtil],
        ///								   [TemValidade],[DataValidade],[Fornecedor],[CustoUnitario],[TempoReceber],[QuantidadeEstoque],[EstoqueMinimo],
        ///								   [ParaVenda],[ParaFabricacao],[ParaUsoInterno],[EstadoEstoque],[Unidade],[Armazem],[DadosAdicionais],[DtCriacao],
        ///								   [UsuarioCriacao],[DtUltimaMod],[UsuarioUltimaMod])
        ///						   VALUES (@ID, @DEC, @TP, @SBTP, @UN, @TPGESTAO, @TMP,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CADASTRA_INVENTARIO_FERRAMENTAS {
            get {
                return ResourceManager.GetString("CADASTRA_INVENTARIO_FERRAMENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO OrcamentosItens (IdOrcamento, IdProduto, IdTipoItemOrc, NomeTipoItemOrc, DescTipoItemOrc, 
        ///							 CaminhoWin, GeoLoc, Descricao, CustoUnitario ,CustoTotal, DescontoPadrao,
        ///							 Quantidade, Observacao, TempoProcesso, TempoTotal, Ativo, DtCriacao,
        ///							 UsuarioCriacao, DtUltimaMod, UsuarioUltMod)
        ///					 VALUES (@IDORC, @IDPROD, @IDTIPO, @NOME, @DESCITEM,
        ///							 @CAMIWIN, @GEO, @DESC, @CUSUNI, @CUSTOT, @DESCONTO,
        ///							 @QTDE, @OBS, @TEMPOU, @TEMPOT, 1, GETDATE(),
        ///							 @USR, GETDAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CADASTRA_ITENS_ORCAMENTO {
            get {
                return ResourceManager.GetString("CADASTRA_ITENS_ORCAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into HistoricoModInventarioFerramentas (IdTool, InfoModificacoes, UsuarioResp, DtModificacao)
        ///values (@TOOLID, @INFO, @USR, GETDATE());
        ///
        ///insert into MovimentoInventariosFerramentas (IdTool, Acao, Motivo, Quantidade, Fornecedor, Unidade, Armazem, Lote, Descricao, DtCriacao, UsuarioCriacao)
        ///values (@TOOLID, @ACAO, @MOTIVO, @QTDE, @FOR, @UNI, @ARM, @LOTE, @DES, GETDATE(), @USR).
        /// </summary>
        internal static string CADASTRA_MOV_EST_INVENTARIO_TOOL {
            get {
                return ResourceManager.GetString("CADASTRA_MOV_EST_INVENTARIO_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE @TABELA ADD @COLUNA @TIPO NULL DEFAULT @VALOR_DEFAULT.
        /// </summary>
        internal static string CADASTRA_NOVA_COLUNA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into PresetsFerramentas (id_Mqn, ToolName, ToolPosition, ToolPreset, ToolDiameter, ToolCoolant, ToolInsert, ToolEnvironment, ToolType)
        ///					    values (@idMqn, @name, @position, @preset, @diam, @coolant, @insert, @envi, @type).
        /// </summary>
        internal static string CADASTRA_NOVA_FERRAMENTA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_FERRAMENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Maquinas (NomeMaquina,MqnAtiva,CaminhoPosCompilado,CaminhoPosCgd,CaminhoCnc,Ambiente,VersaoEcPos,
        ///					  Tecnologia,CustoHoraMqn,CustoHoraHomem,Descricao,UnidadeFabril,DadosAux1,DadosAux2,DadosAux3)
        ///			  values (@NOME, @ATIVO, @MCP, @CGD, @CNC, @ENV, @VER,
        ///					  @EIXO, @HORAMQN, @HORAHM, @DESC, @UNI, @DA1, @DA2, @DA3);.
        /// </summary>
        internal static string CADASTRA_NOVA_MAQUINA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_MAQUINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Ordens (OrdemProducao, PedidoVenda, Cliente, Material, UsuarioResp, Ambiente, Estado, NomePeca, CaminhoPeca, EstadoOperacao, CentroTrabalho, Trabalho, 
        ///					QuantidadeSolicitada, QuantidadeRealizada, DataRequerida, DataEntrega, Descricao, DadosAux1, DadosAux2, DadosAux3, DadosAux4,
        ///					DadosAux5, DadosAux6, DadosAux7, DadosAux8, IsOpened, UsuarioTrabalhando, UsuarioCriacao, DtCriacao, UsuarioUltimaMod, DtUltimaMod)
        ///			values (@ORDEM, @PEDIDO, @CLIENTE, @MAT, @USR, @AMBIENTE, @ESTADO, @PECA,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CADASTRA_NOVA_ORDEM_PRODUCAO {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_ORDEM_PRODUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ConfigReferenciasAutomaticas (Tabela, Coluna, Prefixo, Incremento, ValorInicial, ValorFinal, ContadorAtual, InserirZeros, ZerosAesquerda, ZerosAdireita, NumZerosInserir, UltDataMod)
        ///								  values (@TBL, @CLM, @PRE, @INC, @VI, @VF, @VA, @INSZEROS, @ESQ, @DIR, @NUMZEROS, @DT);.
        /// </summary>
        internal static string CADASTRA_NOVA_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Tarefas (Assunto, Instrucoes, TipoTarefa, PrioridadeTarefa, DtInicio, DtLimite, DtCriacao, UsuarioDesignado, UsuarioSolicitante, ExecucaoRecursiva, Lido, Completo)
        ///			VALUES	(@ASSUNTO, @INSTRU, @TIPO, @PRIORIDADE, @DTINICIO, @DTFIM, @DTCRIACAO, @USR, @USRSOLICITANTE, 0, 0, 0).
        /// </summary>
        internal static string CADASTRA_NOVA_TAREFA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Tarifas (Tarifa, Descricao, Prioridade, PorcentagemTarifa, PorcentagemLucro, TemValidade, TarifaValidaAte, 
        ///					 CtrlVersao, Versao, DtCriacao, UsuarioCriacao, DtUltimaMod, UsuarioUltimaMod)
        ///			values  (@NOME, @DESC, @PRIO, @VALOR, @LUCRO, @HASVALIDITY, @DTEXPIRY,
        ///					 @CTRLVER, @VER, GETDATE(), @USR, GETDATE(), @USR);
        ///
        ///select top 1 id from Tarifas order by id desc.
        /// </summary>
        internal static string CADASTRA_NOVA_TARIFA {
            get {
                return ResourceManager.GetString("CADASTRA_NOVA_TARIFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Arquivos (CaminhoArquivo, Extensao, ArquivoExiste, Ativo, UsuarioResp, DtCadastro) VALUES (@PATH, @EXT, 1, 1, @USR, GETDATE());.
        /// </summary>
        internal static string CADASTRA_NOVO_ARQUIVO_AUXILIAR {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_ARQUIVO_AUXILIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ConfigOrdensExportar (NomeCampo, NomeExportar, Ativo, AceitarValoresVazios, ValorPadrao, UsuarioResp, DtCriacao, DtUltimaMod)
        ///     VALUES (@NOME_DB, @NOME_XML, @ATIVO, @ACEITAR_NULL, @DEFAULT, @USR, @DTC, @DTM).
        /// </summary>
        internal static string CADASTRA_NOVO_CAMPO_EXPORTAR {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_CAMPO_EXPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ConfigOrdensImportar (NomeCampo, NomeImportar, Ativo, AceitarValoresVazios, ValorPadrao, UsuarioResp, DtCriacao, DtUltimaMod)
        ///     VALUES (@NOME_DB, @NOME_XML, @ATIVO, @ACEITAR_NULL, @DEFAULT, @USR, @DTC, @DTM).
        /// </summary>
        internal static string CADASTRA_NOVO_CAMPO_IMPORTAR {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_CAMPO_IMPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CustosAdicionais (CustoAdicional, CustoUnitario, QuantidadePadrao, Ativo, UsuarioResp, DtCadastro)
        ///values (@DESC, @CUSTO, @QTDE, 1, @USR, GETDATE()).
        /// </summary>
        internal static string CADASTRA_NOVO_CUSTO_ADICIONAL {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_CUSTO_ADICIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into DadosAuxiliares (DadoAuxiliar, Ativo, UsuarioResp, DtCadastro) values (@DADOAUX, 1, @USR, GETDATE()).
        /// </summary>
        internal static string CADASTRA_NOVO_DADO_AUXILIAR {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_DADO_AUXILIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Filtros] ([Interface],[Modulo],[Usuario],[IdUsuario],[NomeFiltro],[Private],
        ///						     [Filters],[DtCriacao],[DtUltModificacao])
        ///					VALUES   (@INTER, @MOD, @USR, @ID, @NAME, @PRIV,
        ///						      @FILTERS, GETDATE(), GETDATE());.
        /// </summary>
        internal static string CADASTRA_NOVO_FILTRO_INTERFACE {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_FILTRO_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Impostos (Imposto, Descricao, Prioridade, TipoImposto, ValorImposto, TipoCobrancaImposto, TemValidade, ImpostoValidaAte, 
        ///					 CtrlVersao, Versao, DtCriacao, UsuarioCriacao, DtUltimaMod, UsuarioUltimaMod)
        ///			values  (@NOME, @DESC, @PRIO, @TIPO, @VALOR, @TIPO_VALOR, @HASVALIDITY, @DTEXPIRY,
        ///					 @CTRLVER, @VER, GETDATE(), @USR, GETDATE(), @USR);
        ///
        ///select top 1 id from Impostos order by id desc.
        /// </summary>
        internal static string CADASTRA_NOVO_IMPOSTO {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_IMPOSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Markup ([Nome],[MargemLucro],[Markup],[MarkDown],[MultiplicadorValor],[MultiplicadorPercentual],
        ///					[Ativo],[Visivel],[DtCriacao],[UsuarioCriacao])
        ///			VALUES (@NOME, @MARGEM, @MK, @MKDOWN, @MUL, @MULPER,
        ///					1, 1, GETDATE(), @USR);
        ///
        ///SELECT TOP 1 id FROM Markup order by id desc.
        /// </summary>
        internal static string CADASTRA_NOVO_MARKUP {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_MARKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Orcamentos] ([Orcamento],[Cliente],[Contato],[Cidade],[UF],[Pais],[EstadoOrcamento],[TipoVisi],
        ///								[IdTipoOrcamento],[TipoOrcamento],[IdTipoPag],[NomePag],[OrcOrigem],[IdMoeda],[NomeMoeda],
        ///								[ValorMoeda],[PossuiDesconto],[ValorDesconto],[FreteIncluso],[ValorFrete],[TipoVenda],[ValorSomarVenda],
        ///								[ValorTotal],[ValorTotalComDesconto],[Vendedor],[Orcamentista],[DtCotacao],[DtEmissao],[DtValidade],[DtPrevEntrega],[Versao],[Ativo],
        ///								[UsuarioCriacao],[DtCriacao],[U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CADASTRA_NOVO_ORCAMENTO {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_ORCAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TiposOrcamentos (Nome, Descricao, Categoria, Ativo, DtCriacao, UsuarioResp)
        ///				     VALUES (@NOME, @DESC, @CAT, 1, GETDATE(), @USR);
        ///
        ///SELECT top 1 * FROM TiposOrcamentos ORDER BY id DESC.
        /// </summary>
        internal static string CADASTRA_NOVO_TIPO_ORCAMENTO {
            get {
                return ResourceManager.GetString("CADASTRA_NOVO_TIPO_ORCAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[UsuariosSolicitados] ([Nome],[Sobrenome],[Area],[Gestor],[Email],[Ramal],
        ///										 [UnidadeOrg],[DtReq],[Viewed])
        ///								VALUES  (@NOME, @SOBREN, @AREA, @GESTOR, @EMAIL, @RAMAL,
        ///										 @UNID, GETDATE(), 0);
        ///
        ///select top 1 id from UsuariosSolicitados order by id desc.
        /// </summary>
        internal static string CADASTRA_SOLI_NEW_USER {
            get {
                return ResourceManager.GetString("CADASTRA_SOLI_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Orcamentos SET EstadoOrcamento = 5, Ativo = 0 WHERE ID = @ID.
        /// </summary>
        internal static string CANCELA_ORCAMENTO_POR_ID {
            get {
                return ResourceManager.GetString("CANCELA_ORCAMENTO_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Ordens SET Estado = 6 WHERE ID = @ID.
        /// </summary>
        internal static string CANCELA_ORDEM_DE_PRODUCAO_POR_ID {
            get {
                return ResourceManager.GetString("CANCELA_ORDEM_DE_PRODUCAO_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @IDORDEM as integer = (select id from Ordens where Trabalho = @JOBNAME);
        ///
        ///insert into HistoricoModOrdens (IdOrdem, InfoModificacoes, UsuarioResp, DtModificacao)
        ///values (@IDORDEM, @INFO, @USR, GETDATE());
        ///
        ///update Ordens set Estado = 6 where Trabalho = @JOBNAME.
        /// </summary>
        internal static string CANCELA_ORDEM_DE_PRODUCAO_POR_TRABALHO {
            get {
                return ResourceManager.GetString("CANCELA_ORDEM_DE_PRODUCAO_POR_TRABALHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Tarefas set Completo = 1, Lido = 1 where id = @IDTASK.
        /// </summary>
        internal static string CONCLUI_TAREFA {
            get {
                return ResourceManager.GetString("CONCLUI_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct NomeArmazem from Armazens.
        /// </summary>
        internal static string CONSULTA_ARMAZENS {
            get {
                return ResourceManager.GetString("CONSULTA_ARMAZENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		CaminhoArquivo as &apos;Arquivo&apos;,
        ///		Extensao,
        ///		ArquivoExiste,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro,
        ///		&apos;Selecionar&apos; as &apos;Selecionar&apos;
        ///from Arquivos
        ///where CaminhoArquivo != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_ARQUIVOS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_ARQUIVOS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		CaminhoArquivo as &apos;Arquivo&apos;,
        ///		Extensao,
        ///		ArquivoExiste,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///from Arquivos
        ///where CaminhoArquivo != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_ARQUIVOS_POR_ID {
            get {
                return ResourceManager.GetString("CONSULTA_ARQUIVOS_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	Arquivos.id,
        ///		CaminhoArquivo as &apos;Arquivo&apos;,
        ///		Extensao,
        ///		ArquivoExiste,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///from Arquivos
        ///	inner join ArquivosOrdens
        ///		on Arquivos.id  = ArquivosOrdens.IdArquivo
        ///where ArquivosOrdens.IdOrdem = @ID.
        /// </summary>
        internal static string CONSULTA_ARQUIVOS_POR_ID_ORDEM {
            get {
                return ResourceManager.GetString("CONSULTA_ARQUIVOS_POR_ID_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Artigos.
        /// </summary>
        internal static string CONSULTA_ARTIGOS {
            get {
                return ResourceManager.GetString("CONSULTA_ARTIGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct NomeCampo from ConfigOrdensExportar.
        /// </summary>
        internal static string CONSULTA_CAMPOS_CONFIGURADOS_EXPORTACAO {
            get {
                return ResourceManager.GetString("CONSULTA_CAMPOS_CONFIGURADOS_EXPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct NomeCampo from ConfigOrdensImportar.
        /// </summary>
        internal static string CONSULTA_CAMPOS_CONFIGURADOS_IMPORTACAO {
            get {
                return ResourceManager.GetString("CONSULTA_CAMPOS_CONFIGURADOS_IMPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	id,
        ///		NomeCampo AS &apos;Nome do campo&apos;,
        ///		NomeExportar AS &apos;Nome do elemento para Exportação&apos;,
        ///		Ativo AS &apos;Ativo_Db&apos;,
        ///		AceitarValoresVazios,
        ///		ValorPadrao
        ///FROM ConfigOrdensExportar.
        /// </summary>
        internal static string CONSULTA_CAMPOS_EXPORTAR {
            get {
                return ResourceManager.GetString("CONSULTA_CAMPOS_EXPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	id,
        ///		NomeCampo AS &apos;Nome do campo&apos;,
        ///		NomeImportar AS &apos;Nome do elemento para importação&apos;,
        ///		Ativo AS &apos;Ativo_Db&apos;,
        ///		AceitarValoresVazios,
        ///		ValorPadrao
        ///FROM ConfigOrdensImportar.
        /// </summary>
        internal static string CONSULTA_CAMPOS_IMPORTAR {
            get {
                return ResourceManager.GetString("CONSULTA_CAMPOS_IMPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		Cidade,
        ///		Estado,
        ///		UF,
        ///		Pais as &apos;País&apos;
        ///from Cidades
        ///where id &gt; 0.
        /// </summary>
        internal static string CONSULTA_CIDADES_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_CIDADES_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		NomeEmpresa,
        ///		Setor,
        ///		Endereco,
        ///		Cep,
        ///		Cidade,
        ///		Estado,
        ///		Pais,
        ///		CNPJ,
        ///		NomeInterno,
        ///		Telefone,
        ///		Email,
        ///		IsCliente,
        ///		IsFornecedor,
        ///		IsDistribuidor,
        ///		DtCriacao,
        ///		DtUltimaMod,
        ///		UsuarioUltimaMod
        ///from Clientes.
        /// </summary>
        internal static string CONSULTA_CLIENTES {
            get {
                return ResourceManager.GetString("CONSULTA_CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		NomeEmpresa as &apos;Nome do cliente&apos;,
        ///		Cidade,
        ///		Estado,
        ///		Pais as &apos;País&apos;
        ///from Clientes
        ///where IsCliente = 1.
        /// </summary>
        internal static string CONSULTA_CLIENTES_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_CLIENTES_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select COLUMN_NAME from INFORMATION_SCHEMA.COLUMNS
        ///where DATA_TYPE != &apos;varbinary&apos; and
        ///	  TABLE_NAME = &apos;Ordens&apos; and COLUMN_NAME != &apos;id&apos;.
        /// </summary>
        internal static string CONSULTA_COLUNAS_TABELA_ORDENS {
            get {
                return ResourceManager.GetString("CONSULTA_COLUNAS_TABELA_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		CONCAT(Nome, &apos; &apos;, SobreNome) as Nome,
        ///		Cliente,
        ///		Cidade,
        ///		Estado,
        ///		Pais as &apos;País&apos;
        ///from ContatosClientes
        ///where Ativo = 1.
        /// </summary>
        internal static string CONSULTA_CONTATOS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_CONTATOS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select MoedaPesquisa from Cotacao where Ativo = 1.
        /// </summary>
        internal static string CONSULTA_COTACOES_ATIVAS {
            get {
                return ResourceManager.GetString("CONSULTA_COTACOES_ATIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	&apos;Selecione&apos;as &apos;Selecionar&apos;,
        ///		id,
        ///		MoedaPesquisada as &apos;Moeda&apos;,
        ///		ValorAtual as &apos;Valor da cotação&apos;,
        ///		DtConsulta as &apos;Data de cotação&apos;
        ///from CotacaoDoDia
        ///where id &gt; 0.
        /// </summary>
        internal static string CONSULTA_COTACOES_DIARIAS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_COTACOES_DIARIAS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct CentroTrabalho, Material from Ordens where Estado = 1.
        /// </summary>
        internal static string CONSULTA_CTS_MATERIAIS_DAS_ORDENS {
            get {
                return ResourceManager.GetString("CONSULTA_CTS_MATERIAIS_DAS_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecionar&apos; as &apos;Selecionar&apos;, 
        ///		CustoAdicional as &apos;Custo adicional&apos;,
        ///		CustoUnitario as &apos;Custo unitário (R$)&apos;,
        ///		QuantidadePadrao as &apos;Quantidade&apos;,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///from CustosAdicionais
        ///where CustoAdicional != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_CUSTOS_ADICIONAIS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_CUSTOS_ADICIONAIS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id, 
        ///		CustoAdicional as &apos;Custo adicional&apos;,
        ///		CustoUnitario as &apos;Custo unitário (R$)&apos;,
        ///		QuantidadePadrao as &apos;Quantidade&apos;,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///from CustosAdicionais
        ///where CustoAdicional != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_CUSTOS_ADICIONAIS_POR_ID {
            get {
                return ResourceManager.GetString("CONSULTA_CUSTOS_ADICIONAIS_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  Descricao AS &apos;Descrição do item&apos;,
        ///		Tipo,
        ///		Valor
        ///FROM OrcamentosDetaCustos
        ///WHERE IdOrcamento = @ID.
        /// </summary>
        internal static string CONSULTA_CUSTOS_DETALHADOS_ORCAMENTO {
            get {
                return ResourceManager.GetString("CONSULTA_CUSTOS_DETALHADOS_ORCAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	&apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		id,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		Material,
        ///		DensidadeMaterial as &apos;Densidade&apos;,
        ///		ValorPrecoQuilo,
        ///		Fornecedor,
        ///		OfertaValidaAte as &apos;Válido até&apos;
        ///FROM CustosMateriais.
        /// </summary>
        internal static string CONSULTA_CUSTOS_MATERIAIS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_CUSTOS_MATERIAIS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	id,
        ///		DadoAuxiliar AS &apos;Dado auxiliar&apos;,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///FROM DadosAuxiliares
        ///WHERE DadoAuxiliar != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_DADOS_AUXILIARES_POR_ID {
            get {
                return ResourceManager.GetString("CONSULTA_DADOS_AUXILIARES_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	DadosAuxiliares.id,
        ///		DadoAuxiliar AS &apos;Dado auxiliar&apos;,
        ///		Ativo as &apos;Ativo_Db&apos;,
        ///		UsuarioResp,
        ///		DtCadastro
        ///FROM DadosAuxiliares
        ///	INNER JOIN DadosAuxiliaresOrdens
        ///		on DadosAuxiliares.id = DadosAuxiliaresOrdens.IdDadoAuxiliar
        ///WHERE DadosAuxiliaresOrdens.IdOrdem = @ID.
        /// </summary>
        internal static string CONSULTA_DADOS_AUXILIARES_POR_ID_ORDEM {
            get {
                return ResourceManager.GetString("CONSULTA_DADOS_AUXILIARES_POR_ID_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		Estado,
        ///		UF,
        ///		Pais as &apos;País&apos;
        ///from Estados
        ///where id &gt; 0.
        /// </summary>
        internal static string CONSULTA_ESTADOS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_ESTADOS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Calendario where VisivelATodos = 1 or Proprietario = @USR.
        /// </summary>
        internal static string CONSULTA_EVENTOS_CALENDARIO {
            get {
                return ResourceManager.GetString("CONSULTA_EVENTOS_CALENDARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from ConfigLockedExtension.
        /// </summary>
        internal static string CONSULTA_EXTENSOES_BLOQUEADAS {
            get {
                return ResourceManager.GetString("CONSULTA_EXTENSOES_BLOQUEADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from ConfigUnlockedExtension.
        /// </summary>
        internal static string CONSULTA_EXTENSOES_PERMITIDAS {
            get {
                return ResourceManager.GetString("CONSULTA_EXTENSOES_PERMITIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from ConfigExportOrders.
        /// </summary>
        internal static string CONSULTA_FIELDS_EXPORTAR {
            get {
                return ResourceManager.GetString("CONSULTA_FIELDS_EXPORTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct Fornecedor from Fornecedores.
        /// </summary>
        internal static string CONSULTA_FORNECEDORES {
            get {
                return ResourceManager.GetString("CONSULTA_FORNECEDORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		IdTool,
        ///		InfoModificacoes as &apos;Detalhe&apos;,
        ///		UsuarioResp as &apos;Usuário responsável&apos;,
        ///		DtModificacao as &apos;Data de registro&apos;
        ///from HistoricoModInventarioFerramentas
        ///where IdTool = @IDTOOL.
        /// </summary>
        internal static string CONSULTA_HISTORICO_INVENTARIO_TOOL {
            get {
                return ResourceManager.GetString("CONSULTA_HISTORICO_INVENTARIO_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		IdOrcamento,
        ///		InfoModificacoes as &apos;Detalhe&apos;,
        ///		UsuarioResp as &apos;Usuário responsável&apos;,
        ///		DtModificacao as &apos;Data de registro&apos;,
        ///		Versao as &apos;Versão&apos;
        ///from HistoricoModOrcamentos
        ///where IdOrcamento = @ID.
        /// </summary>
        internal static string CONSULTA_HISTORICO_ORCAMENTOS {
            get {
                return ResourceManager.GetString("CONSULTA_HISTORICO_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		IdOrdem,
        ///		InfoModificacoes as &apos;Detalhe&apos;,
        ///		UsuarioResp as &apos;Usuário responsável&apos;,
        ///		DtModificacao as &apos;Data de registro&apos;
        ///from HistoricoModOrdens
        ///where IdOrdem = @IDORDEM.
        /// </summary>
        internal static string CONSULTA_HISTORICO_ORDENS {
            get {
                return ResourceManager.GetString("CONSULTA_HISTORICO_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		IdJob,
        ///		InfoModificacoes as &apos;Detalhe&apos;,
        ///		UsuarioResp as &apos;Usuário responsável&apos;,
        ///		DtModificacao as &apos;Data de registro&apos;
        ///from HistoricoModTrabalhos
        ///where IdJob = @IDJOB.
        /// </summary>
        internal static string CONSULTA_HISTORICO_TRABALHOS {
            get {
                return ResourceManager.GetString("CONSULTA_HISTORICO_TRABALHOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM IcmsEstaduais WHERE EstadoOrig = @EO AND EstadoDest = @ED.
        /// </summary>
        internal static string CONSULTA_ICMS_ESTADUAIS {
            get {
                return ResourceManager.GetString("CONSULTA_ICMS_ESTADUAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id_Mqn from Maquinas where NomeMaquina = @MqnName.
        /// </summary>
        internal static string CONSULTA_ID_MAQUINA {
            get {
                return ResourceManager.GetString("CONSULTA_ID_MAQUINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	&apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		id,
        ///		Imposto,
        ///		TipoImposto,
        ///		&apos;&apos; as &apos;Tipo de imposto&apos;,
        ///		ValorImposto,
        ///		&apos;&apos; as &apos;Valor do imposto&apos;,
        ///		TemValidade,
        ///		ImpostoValidaAte as &apos;Válido até&apos;
        ///from Impostos
        ///where Imposto != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_IMPOSTOS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_IMPOSTOS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		Imposto,
        ///		TipoImposto,
        ///		&apos;&apos; as &apos;Tipo de imposto&apos;,
        ///		ValorImposto,
        ///		&apos;&apos; as &apos;Valor do imposto&apos;,
        ///		TemValidade,
        ///		ImpostoValidaAte as &apos;Válido até&apos;
        ///from Impostos
        ///where Imposto != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_IMPOSTOS_POR_ID {
            get {
                return ResourceManager.GetString("CONSULTA_IMPOSTOS_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [id],
        ///       [IdTool] as &apos;Id da ferramenta&apos;,
        ///       [DescricaoTool] as &apos;Nome da ferramenta&apos;,
        ///       [TipoTool] as &apos;Tipo_Db&apos;,
        ///       [SubTipoTool] as &apos;SubTipo_Db&apos;,
        ///       [UnidadeMedida] as &apos;Unidade_Db&apos;,
        ///       [TipoGestaoVidaUtil] as &apos;TipoGestao_Db&apos;,
        ///       [TempoVidaUtil] as &apos;Tempo de vida útil&apos;,
        ///       [TemValidade] as &apos;Possui validade&apos;,
        ///       [DataValidade] as &apos;Data de validade&apos;,
        ///       [Fornecedor],
        ///       [CustoUnitario] as &apos;Custo unitário&apos;,
        ///       [TempoReceber] as &apos;Tempo para rece [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_INVENTARIO_FERRAMENTAS {
            get {
                return ResourceManager.GetString("CONSULTA_INVENTARIO_FERRAMENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	NomeTipoItemOrc as &apos;Item&apos;,
        ///		CustoUnitario as &apos;Custo unitário (R$)&apos;,
        ///		CustoTotal as &apos;Custo total (R$)&apos;,
        ///		Quantidade,
        ///		CaminhoWin as &apos;CaminhoDoItem&apos;,
        ///		TempoProcesso as &apos;Tempo do processo&apos;,
        ///		TempoTotal as &apos;Tempo total&apos;,
        ///		IdTipoItemOrc as &apos;IdTipoItensOrcamento&apos;
        ///FROM OrcamentosItens
        ///WHERE IdOrcamento = @ID.
        /// </summary>
        internal static string CONSULTA_ITENS_ORCAMENTOS {
            get {
                return ResourceManager.GetString("CONSULTA_ITENS_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Login from Usuarios order by Login.
        /// </summary>
        internal static string CONSULTA_LISTA_USUARIOS {
            get {
                return ResourceManager.GetString("CONSULTA_LISTA_USUARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from PresetsFerramentas where id_Mqn = @IDMQN order by ToolPosition.
        /// </summary>
        internal static string CONSULTA_MAGAZINE_MQN {
            get {
                return ResourceManager.GetString("CONSULTA_MAGAZINE_MQN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		NomeMaquina as &apos;Centro de trabalho&apos;,
        ///		MqnAtiva as &apos;MqnAtiva_Db&apos;,
        ///		CaminhoPosCompilado,
        ///		CaminhoPosCgd,
        ///		CaminhoCnc,
        ///		Ambiente as &apos;Ambiente_Db&apos;,
        ///		VersaoEcPos,
        ///		Tecnologia,
        ///		CustoHoraMqn,
        ///		CustoHoraHomem,
        ///		Descricao,
        ///		UnidadeFabril as &apos;Unidade&apos;,
        ///		DadosAux1,
        ///		DadosAux2,
        ///		DadosAux3
        ///from Maquinas 
        ///where NomeMaquina is not null.
        /// </summary>
        internal static string CONSULTA_MAQUINAS {
            get {
                return ResourceManager.GetString("CONSULTA_MAQUINAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///	   id,
        ///	   Nome,
        ///	   MargemLucro as &apos;Margem de lucro (%)&apos;,
        ///	   Markup,
        ///	   MarkDown,
        ///	   MultiplicadorValor,
        ///	   MultiplicadorPercentual,
        ///	   Ativo as &apos;Ativo_db&apos;,
        ///	   Visivel as &apos;Visível&apos;,
        ///	   DtCriacao as &apos;Data de cadastro&apos;,
        ///	   UsuarioCriacao as &apos;Cadastrado por&apos;
        ///FROM Markup
        ///WHERE Nome IS NOT NULL.
        /// </summary>
        internal static string CONSULTA_MARKUPS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_MARKUPS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	&apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		id,
        ///		NomeMaterial as &apos;Material&apos;,
        ///		Densidade,
        ///		Ativo as &apos;Ativo_Db&apos;
        ///from Materiais
        ///where NomeMaterial is not null.
        /// </summary>
        internal static string CONSULTA_MATERIAIS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_MATERIAIS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from ConfigIgnoredModels.
        /// </summary>
        internal static string CONSULTA_MODELOS_IGNORADOS {
            get {
                return ResourceManager.GetString("CONSULTA_MODELOS_IGNORADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	&apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		id,
        ///		MoedaPesquisa as &apos;Moeda&apos;,
        ///		Ativo as &apos;Ativo_Db&apos;
        ///from Cotacao
        ///where MoedaPesquisa is not null.
        /// </summary>
        internal static string CONSULTA_MOEDAS_COTACOES_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_MOEDAS_COTACOES_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		IdTool,
        ///		Acao,
        ///		Motivo,
        ///		Quantidade,
        ///		Fornecedor,
        ///		Unidade,
        ///		Armazem as &apos;Armazém&apos;,
        ///		Lote,
        ///		Descricao as &apos;Descrição&apos;,
        ///		DtCriacao as &apos;Data de registro&apos;,
        ///		UsuarioCriacao as &apos;Usuário responsável&apos;
        ///from MovimentoInventariosFerramentas.
        /// </summary>
        internal static string CONSULTA_MOVIMENTOS_INVENTARIO_TOOL {
            get {
                return ResourceManager.GetString("CONSULTA_MOVIMENTOS_INVENTARIO_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	COLUMN_NAME AS &apos;Coluna&apos;,
        ///		&apos;Tipo&apos; = 
        ///		(
        ///			CASE WHEN DATA_TYPE = &apos;int&apos; THEN &apos;Inteiro&apos;
        ///				 WHEN DATA_TYPE = &apos;nvarchar&apos; THEN &apos;Texto&apos;
        ///				 WHEN DATA_TYPE = &apos;nchar&apos; THEN &apos;Caractere&apos;
        ///				 WHEN DATA_TYPE = &apos;date&apos; THEN &apos;Data&apos;
        ///				 WHEN DATA_TYPE = &apos;datetime&apos; THEN &apos;Data e hora&apos;
        ///				 WHEN DATA_TYPE = &apos;float&apos; THEN &apos;Real&apos;				 
        ///				 WHEN DATA_TYPE = &apos;varbinary&apos; THEN &apos;Imagem&apos;
        ///				 WHEN DATA_TYPE = &apos;bit&apos; THEN &apos;Verdadeiro ou falso&apos;
        ///				 ELSE &apos;Unknown&apos;
        ///			END
        ///		),
        ///		&apos;Criado por&apos; = CASE WHEN COLUMN_NA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_NOMES_COLUNAS_PERSONALIZAR {
            get {
                return ResourceManager.GetString("CONSULTA_NOMES_COLUNAS_PERSONALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sys.tables.name from sys.tables 
        ///where sys.tables.name != &apos;ConfigReferenciasAutomaticas&apos;.
        /// </summary>
        internal static string CONSULTA_NOMES_TABELAS {
            get {
                return ResourceManager.GetString("CONSULTA_NOMES_TABELAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	&apos;Selecionar&apos; AS &apos;Selecionar&apos;,
        ///		TABLE_NAME AS &apos;Tabela&apos; FROM INFORMATION_SCHEMA.COLUMNS
        ///WHERE TABLE_NAME NOT LIKE &apos;%Config%&apos;
        ///GROUP BY TABLE_NAME.
        /// </summary>
        internal static string CONSULTA_NOMES_TABELAS_PERSONALIZAR {
            get {
                return ResourceManager.GetString("CONSULTA_NOMES_TABELAS_PERSONALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id,
        ///       Orcamento as &apos;Orçamento&apos;,
        ///       Cliente,
        ///       Contato,
        ///       Cidade,
        ///       UF as &apos;Unidade da federação&apos;,
        ///       Pais as &apos;País&apos;,
        ///       EstadoOrcamento as &apos;EstadoOrcamento_db&apos;,
        ///       TipoVisi as &apos;Visibilidade_db&apos;,
        ///       IdTipoOrcamento,
        ///	   TipoOrcamento as &apos;Tipo de orçamento&apos;,
        ///       IdTipoPag,
        ///	   NomePag as &apos;Forma de pagamento&apos;,
        ///       OrcOrigem as OrcOrigem_db,
        ///	   &apos;&apos; as &apos;Origem do orçamento&apos;,
        ///       IdMoeda,
        ///	   NomeMoeda as &apos;Moeda utilizada&apos;,
        ///       isnull(Valo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_ORCAMENTOS {
            get {
                return ResourceManager.GetString("CONSULTA_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		OrdemProducao as &apos;Ordem de produção&apos;,
        ///		PedidoVenda as &apos;Pedido&apos;,
        ///		Cliente,
        ///		Material,
        ///		UsuarioResp as &apos;Usuário responsável&apos;,
        ///		Ambiente as &apos;Ambiente_Db&apos;,
        ///		Estado as &apos;Estado_Db&apos;,
        ///		NomePeca as &apos;Peça&apos;,
        ///		CaminhoPeca,
        ///		EstadoOperacao as &apos;Estado da operação&apos;,
        ///		CentroTrabalho as &apos;Centro de trabalho&apos;,
        ///		Trabalho,
        ///		QuantidadeSolicitada as &apos;Solicitado&apos;,
        ///		QuantidadeRealizada as &apos;Realizado&apos;,
        ///		DataRequerida as &apos;Data de solicitação&apos;,
        ///		DataEntrega as &apos;Data de entrega&apos;,
        ///		Descricao [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_ORDENS {
            get {
                return ResourceManager.GetString("CONSULTA_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		Pais as &apos;País&apos;,
        ///		Continente 
        ///from Paises
        ///where id &gt; 0.
        /// </summary>
        internal static string CONSULTA_PAISES_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_PAISES_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	P.id,
        ///		&apos;Selecione&apos; as Selecionar,
        ///		P.Nome,
        ///		P.Descricao as &apos;Descrição&apos;,
        ///		P.CustoUnitario as &apos;Custo unitário&apos;,
        ///		P.CustoTotal as &apos;Custo total&apos;,
        ///		P.DescontoPadrao as &apos;Desconto padrão&apos;,
        ///		P.Quantidade,
        ///		P.Tipo as &apos;Tipo_Db&apos;,
        ///		T.Nome AS &apos;Tipo&apos;,
        ///		P.Observacao as &apos;Observação&apos;,
        ///		P.Ativo as &apos;Ativo_Db&apos;,
        ///		P.DtCriacao as &apos;Data de cadastro&apos;,
        ///		P.UsuarioResp as &apos;Cadastrado por&apos;,
        ///		P.DtUltimaMod as &apos;Data de última mod.&apos;,
        ///		P.UsuarioUltMod as &apos;Última alteração por&apos;
        ///FROM Produtos AS P
        ///	INNE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONSULTA_PRODUTOS {
            get {
                return ResourceManager.GetString("CONSULTA_PRODUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	Tabela,
        ///		Coluna,
        ///		Prefixo,
        ///		ValorFinal,
        ///		ValorInicial,
        ///		ContadorAtual
        ///from ConfigReferenciasAutomaticas.
        /// </summary>
        internal static string CONSULTA_REFERENCIAS_AUTOMATICAS {
            get {
                return ResourceManager.GetString("CONSULTA_REFERENCIAS_AUTOMATICAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		r.NomeRota,
        ///		o.Operacao,
        ///		o.OrdemExecucao,
        ///		o.TempoEstimado,
        ///		o.Custo
        ///from RotasProducao as r
        ///	inner join OperacoesRotasProducao as o
        ///		on o.IdRota = r.id
        ///where r.Ativo = 1.
        /// </summary>
        internal static string CONSULTA_ROTAS_PRODUCAO {
            get {
                return ResourceManager.GetString("CONSULTA_ROTAS_PRODUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TABLE_NAME, COLUMN_NAME from INFORMATION_SCHEMA.COLUMNS
        ///where DATA_TYPE = &apos;nvarchar&apos; and
        ///	  TABLE_NAME not like &apos;%Config%&apos; and TABLE_NAME not like &apos;%sysdiagrams%&apos;.
        /// </summary>
        internal static string CONSULTA_TABELAS {
            get {
                return ResourceManager.GetString("CONSULTA_TABELAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select isnull(count(*), 0) as &apos;Tasks&apos;
        ///from Tarefas 
        ///where Lido = 0 and UsuarioDesignado = @USUARIO.
        /// </summary>
        internal static string CONSULTA_TAREFAS_NAO_LIDAS {
            get {
                return ResourceManager.GetString("CONSULTA_TAREFAS_NAO_LIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		Assunto,
        ///		Instrucoes as &apos;Descrição&apos;,
        ///		TipoTarefa,
        ///		PrioridadeTarefa,--Abaixo será adicionado a prioridade (com imagem)
        ///		DtInicio as &apos;Início&apos;,
        ///		DtLimite,
        ///		DtCriacao as &apos;Requerida&apos;,
        ///		DtUltimaMod,
        ///		UsuarioUltimaMod,
        ///		UsuarioDesignado &apos;Designado&apos;,
        ///		UsuarioSolicitante &apos;Solicitante&apos;,
        ///		ExecucaoRecursiva,
        ///		Periodo,
        ///		DtPeriodoInicio,
        ///		DtPeriodoNext,
        ///		Lido,
        ///		Completo
        ///from Tarefas.
        /// </summary>
        internal static string CONSULTA_TAREFAS_USUARIO_LOGADO {
            get {
                return ResourceManager.GetString("CONSULTA_TAREFAS_USUARIO_LOGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	&apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		id,
        ///		Tarifa,
        ///		PorcentagemTarifa as &apos;Valor (%)&apos;,
        ///		PorcentagemLucro as &apos;Lucro sobre tarifa (%)&apos;,
        ///		TemValidade,
        ///		TarifaValidaAte as &apos;Válido até&apos;
        ///from Tarifas
        ///where Tarifa != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_TARIFAS_FOR_SELECAO {
            get {
                return ResourceManager.GetString("CONSULTA_TARIFAS_FOR_SELECAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		Tarifa,
        ///		PorcentagemTarifa as &apos;Valor (%)&apos;,
        ///		PorcentagemLucro as &apos;Lucro sobre tarifa (%)&apos;,
        ///		TemValidade,
        ///		TarifaValidaAte as &apos;Válido até&apos;
        ///from Tarifas
        ///where Tarifa != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_TARIFAS_POR_ID {
            get {
                return ResourceManager.GetString("CONSULTA_TARIFAS_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Tempo from TemposGastosProgramacao where IdOrdem = @ID.
        /// </summary>
        internal static string CONSULTA_TEMPO_GASTO_ORDEM {
            get {
                return ResourceManager.GetString("CONSULTA_TEMPO_GASTO_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TiposOrcamentos.
        /// </summary>
        internal static string CONSULTA_TIPOS_ORCAMENTOS {
            get {
                return ResourceManager.GetString("CONSULTA_TIPOS_ORCAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from TiposPagamentos.
        /// </summary>
        internal static string CONSULTA_TIPOS_PAGAMENTO {
            get {
                return ResourceManager.GetString("CONSULTA_TIPOS_PAGAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	id,
        ///		MoedaPesquisada,
        ///		ValorAtual as &apos;ValorTexto&apos;,
        ///		&apos;&apos; as ValorNum,
        ///		DtConsulta,
        ///		UsuarioResp
        ///from CotacaoDoDia 
        ///where ValorAtual like &apos;%@MOEDA%&apos; and
        ///cast(DtConsulta as date) between &apos;@DTINICIO&apos; and &apos;@DTFIM&apos;
        ///order by DtConsulta.
        /// </summary>
        internal static string CONSULTA_TODAS_COTACOES_MES_CORRENTE {
            get {
                return ResourceManager.GetString("CONSULTA_TODAS_COTACOES_MES_CORRENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT		id,
        ///			Tabela,
        ///			Coluna,
        ///			Prefixo,
        ///			Incremento,
        ///			ValorInicial,
        ///			ValorFinal,
        ///			ContadorAtual AS &apos;Valor do contador atual&apos;,
        ///			InserirZeros,
        ///			ZerosAesquerda,
        ///			ZerosAdireita,
        ///			NumZerosInserir,
        ///			UltDataMod
        ///FROM ConfigReferenciasAutomaticas.
        /// </summary>
        internal static string CONSULTA_TODAS_REFERENCIAS_AUTOMATICAS {
            get {
                return ResourceManager.GetString("CONSULTA_TODAS_REFERENCIAS_AUTOMATICAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	id,
        ///		DadoAuxiliar AS &apos;Dado auxiliar&apos;,
        ///		Ativo AS &apos;Ativo_Db&apos;,
        ///		&apos;Selecionar&apos; AS &apos;Selecionar&apos;
        ///FROM DadosAuxiliares
        ///WHERE DadoAuxiliar != &apos;&apos;.
        /// </summary>
        internal static string CONSULTA_TODOS_DADOS_AUXILIARES {
            get {
                return ResourceManager.GetString("CONSULTA_TODOS_DADOS_AUXILIARES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ValorAtual, DtConsulta from CotacaoDoDia 
        ///where DtConsulta = (select max(DtConsulta) from CotacaoDoDia where MoedaPesquisada = @MOEDA)
        ///and MoedaPesquisada = @MOEDA.
        /// </summary>
        internal static string CONSULTA_ULTIMA_DATA_COTACAO_MOEDA {
            get {
                return ResourceManager.GetString("CONSULTA_ULTIMA_DATA_COTACAO_MOEDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 id from Arquivos order by id desc.
        /// </summary>
        internal static string CONSULTA_ULTIMO_ID_ARQUIVO {
            get {
                return ResourceManager.GetString("CONSULTA_ULTIMO_ID_ARQUIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 id from CustosAdicionais order by id desc.
        /// </summary>
        internal static string CONSULTA_ULTIMO_ID_CUSTO_ADICIONAL {
            get {
                return ResourceManager.GetString("CONSULTA_ULTIMO_ID_CUSTO_ADICIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 id from DadosAuxiliares order by id desc.
        /// </summary>
        internal static string CONSULTA_ULTIMO_ID_DADO_AUXILIAR {
            get {
                return ResourceManager.GetString("CONSULTA_ULTIMO_ID_DADO_AUXILIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct Unidade from UnidadesOrganizacionais where Ativo = 1.
        /// </summary>
        internal static string CONSULTA_UNIDADES_ORGANIZACIONAIS {
            get {
                return ResourceManager.GetString("CONSULTA_UNIDADES_ORGANIZACIONAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Usuarios where Login = @LOGIN and Senha = @SENHA.
        /// </summary>
        internal static string CONSULTA_USUARIO {
            get {
                return ResourceManager.GetString("CONSULTA_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &apos;Selecione&apos; as &apos;Selecionar&apos;,
        ///		Login as &apos;Usuário&apos;
        ///from Usuarios
        ///where Login != &apos;SYSADM&apos; and Ativo = 1.
        /// </summary>
        internal static string CONSULTA_USUARIOS_PARA_DESIGNAR_ORDENS {
            get {
                return ResourceManager.GetString("CONSULTA_USUARIOS_PARA_DESIGNAR_ORDENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Vendas.
        /// </summary>
        internal static string CONSULTA_VENDAS {
            get {
                return ResourceManager.GetString("CONSULTA_VENDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Versao.
        /// </summary>
        internal static string CONSULTA_VERSAO_DATABASE {
            get {
                return ResourceManager.GetString("CONSULTA_VERSAO_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from UnidadesOrganizacionais.
        /// </summary>
        internal static string CONTULTA_TODAS_UNIDADES_ORGANIZACIONAIS {
            get {
                return ResourceManager.GetString("CONTULTA_TODAS_UNIDADES_ORGANIZACIONAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ConfigOrdensExportar WHERE id = @ID.
        /// </summary>
        internal static string DELETA_CAMPO_EXPORTACAO {
            get {
                return ResourceManager.GetString("DELETA_CAMPO_EXPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ConfigOrdensImportar WHERE id = @ID.
        /// </summary>
        internal static string DELETA_CAMPO_IMPORTACAO {
            get {
                return ResourceManager.GetString("DELETA_CAMPO_IMPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE @TABELA DROP COLUMN @COLUNA;.
        /// </summary>
        internal static string DELETA_COLUNA {
            get {
                return ResourceManager.GetString("DELETA_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ConstraintName nvarchar(200)
        ///SELECT @ConstraintName = Name FROM SYS.DEFAULT_CONSTRAINTS
        ///WHERE PARENT_OBJECT_ID = OBJECT_ID(&apos;@TABELA&apos;)
        ///AND PARENT_COLUMN_ID = (SELECT column_id FROM sys.columns
        ///                        WHERE NAME = N&apos;@COLUNA&apos;
        ///                        AND object_id = OBJECT_ID(N&apos;@TABELA&apos;))
        ///IF @ConstraintName IS NOT NULL
        ///EXEC(&apos;ALTER TABLE @TABELA DROP CONSTRAINT &apos; + @ConstraintName).
        /// </summary>
        internal static string DELETA_CONSTRAINT_COLUNA {
            get {
                return ResourceManager.GetString("DELETA_CONSTRAINT_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from CotacaoDoDia where cast(DtConsulta as date) = &apos;@DT&apos; and MoedaPesquisada = &apos;@MOEDA&apos;.
        /// </summary>
        internal static string DELETA_COTACAO_DIA {
            get {
                return ResourceManager.GetString("DELETA_COTACAO_DIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from ConfigReferenciasAutomaticas where id = @ID.
        /// </summary>
        internal static string DELETA_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("DELETA_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Tarefas where id_Tarefa = @IDTASK.
        /// </summary>
        internal static string DELETA_TAREFA {
            get {
                return ResourceManager.GetString("DELETA_TAREFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Arquivos where CaminhoArquivo = @ARQ.
        /// </summary>
        internal static string EXISTE_ARQUIVO_AUXILIAR_BANCO {
            get {
                return ResourceManager.GetString("EXISTE_ARQUIVO_AUXILIAR_BANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME
        ///FROM INFORMATION_SCHEMA.columns
        ///WHERE TABLE_NAME = @TABELA AND COLUMN_NAME = @COLUNA.
        /// </summary>
        internal static string EXISTE_COLUNA {
            get {
                return ResourceManager.GetString("EXISTE_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ConfigNotificacoes WHERE UsuarioResp = @USUARIO.
        /// </summary>
        internal static string EXISTE_CONFIGURACAO_NOTIFICACOES_USUARIO_ATUAL {
            get {
                return ResourceManager.GetString("EXISTE_CONFIGURACAO_NOTIFICACOES_USUARIO_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from CotacaoDoDia where MoedaPesquisada = @MOEDA and cast(DtConsulta as date) = @DT.
        /// </summary>
        internal static string EXISTE_COTACAO_DE_HOJE {
            get {
                return ResourceManager.GetString("EXISTE_COTACAO_DE_HOJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from ConfigReferenciasAutomaticas where Tabela=@TBL and Coluna=@CLM.
        /// </summary>
        internal static string EXISTE_REFERENCIA_AUTOMATICA {
            get {
                return ResourceManager.GetString("EXISTE_REFERENCIA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensExportar SET Ativo = 0 where id = @ID.
        /// </summary>
        internal static string INATIVA_CAMPO_EXPORTACAO {
            get {
                return ResourceManager.GetString("INATIVA_CAMPO_EXPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ConfigOrdensImportar SET Ativo = 0 where id = @ID.
        /// </summary>
        internal static string INATIVA_CAMPO_IMPORTACAO {
            get {
                return ResourceManager.GetString("INATIVA_CAMPO_IMPORTACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Tarefas set Lido = 1 where id = @ID.
        /// </summary>
        internal static string MARCA_TAREFA_COMO_LIDA {
            get {
                return ResourceManager.GetString("MARCA_TAREFA_COMO_LIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update InventarioFerramentas set QuantidadeEstoque = 0, EstadoEstoque = 0 where id = @ID;.
        /// </summary>
        internal static string REINICIA_ESTOQUE_TOOL {
            get {
                return ResourceManager.GetString("REINICIA_ESTOQUE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Usuarios set Imagem =null where id = @ID.
        /// </summary>
        internal static string REMOVE_FOTO_USUARIO {
            get {
                return ResourceManager.GetString("REMOVE_FOTO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_rename &apos;@TABELA.@COLUNA&apos;, &apos;@NOVA_COLUNA&apos;, &apos;COLUMN&apos;;.
        /// </summary>
        internal static string RENOMEIA_COLUNA {
            get {
                return ResourceManager.GetString("RENOMEIA_COLUNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ConfigNotificacoes (MostrarNotificacoes, Tempo, TempoAnimacao, NotifyNovasOrdens, NotifyNovasOrdensErro, 
        ///								NotifyNovosOrçamentos, NotifyInventario, NotifyEstoqueMinimo, NotifyOrdensAtrasadas,
        ///								UsuarioResp, DtCriacao, DtUltimaMod)
        ///						VALUES (@MOSTRAR, @TEMPO, @TEMPO_ANIMACAO, @ORDENS, @ORDENS_ERRO,
        ///								@ORCAMENTOS, @INVENTARIO, @ESTOQUE, @ORDENS_ATRASADAS,
        ///								@USUARIO, @DATA_CRIACAO, @DATA_ULTMOD).
        /// </summary>
        internal static string SALVA_CONFIGURACOES_NOTIFICACOES {
            get {
                return ResourceManager.GetString("SALVA_CONFIGURACOES_NOTIFICACOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into CotacaoDoDia (MoedaPesquisada, ValorAtual, DtConsulta, UsuarioResp)
        ///values (@MOEDA, @VALOR, @DT, @USR).
        /// </summary>
        internal static string SALVA_COTACAO_DE_HOJE {
            get {
                return ResourceManager.GetString("SALVA_COTACAO_DE_HOJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Ordens set UsuarioResp = @USR where id = @ID.
        /// </summary>
        internal static string TROCA_USUARIO_ORDEM {
            get {
                return ResourceManager.GetString("TROCA_USUARIO_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from InventarioFerramentas where IdTool = @IDTOOL.
        /// </summary>
        internal static string VERIFICA_SE_EXISTE_FERRAMENTA_INVENTARIO {
            get {
                return ResourceManager.GetString("VERIFICA_SE_EXISTE_FERRAMENTA_INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IsOpened, UsuarioTrabalhando FROM Ordens WHERE id = @ID.
        /// </summary>
        internal static string VERIFICA_SE_ORDEM_ESTA_ABERTA {
            get {
                return ResourceManager.GetString("VERIFICA_SE_ORDEM_ESTA_ABERTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ArquivosOrdens (IdArquivo, IdOrdem, DtUltimaMod, Usuario)
        ///VALUES (@DADOAUX, @ORDEM, GETDATE(), @USR).
        /// </summary>
        internal static string VINCULA_ARQUIVO_AUXILIAR_ORDEM {
            get {
                return ResourceManager.GetString("VINCULA_ARQUIVO_AUXILIAR_ORDEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DadosAuxiliaresOrdens (IdDadoAuxiliar, IdOrdem, DtUltimaMod, Usuario)
        ///VALUES (@DADOAUX, @ORDEM, GETDATE(), @USR).
        /// </summary>
        internal static string VINCULA_DADO_AUXILIAR_ORDEM {
            get {
                return ResourceManager.GetString("VINCULA_DADO_AUXILIAR_ORDEM", resourceCulture);
            }
        }
    }
}
