//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgecam_Manager_Arquive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edgecam_Manager_Arquive.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable language.
        /// </summary>
        internal static string msgid_0000 {
            get {
                return ResourceManager.GetString("msgid_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when creating Edgecam Manager folders..
        /// </summary>
        internal static string msgid_0001 {
            get {
                return ResourceManager.GetString("msgid_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not valid (is empty).
        /// </summary>
        internal static string msgid_0002 {
            get {
                return ResourceManager.GetString("msgid_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; not exist, we&apos;ll create now.
        /// </summary>
        internal static string msgid_0003 {
            get {
                return ResourceManager.GetString("msgid_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; exist, will check the permissions.
        /// </summary>
        internal static string msgid_0004 {
            get {
                return ResourceManager.GetString("msgid_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user have enough permissions on folder..
        /// </summary>
        internal static string msgid_0005 {
            get {
                return ResourceManager.GetString("msgid_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn&apos;t have enough permissions on folder..
        /// </summary>
        internal static string msgid_0006 {
            get {
                return ResourceManager.GetString("msgid_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretório não existe ou o caminho informado não é válido.
        /// </summary>
        internal static string msgid_0007 {
            get {
                return ResourceManager.GetString("msgid_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório existe, no entanto, o usuário atual não possuí permissões suficientes para realizar essa ação de conexão..
        /// </summary>
        internal static string msgid_0008 {
            get {
                return ResourceManager.GetString("msgid_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string msgid_0009 {
            get {
                return ResourceManager.GetString("msgid_0009", resourceCulture);
            }
        }
    }
}
