//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgecam_Manager.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edgecam_Manager.Idiomas.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is wasn&apos;t possible to find a configuration file in current system. Please, contact the system administrator or configure the server in system parameters..
        /// </summary>
        internal static string FrmLogin_Arquivo_config_nao_existe {
            get {
                return ResourceManager.GetString("FrmLogin_Arquivo_config_nao_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found a valid configuration.
        /// </summary>
        internal static string FrmLogin_Configuracao_nao_localizada {
            get {
                return ResourceManager.GetString("FrmLogin_Configuracao_nao_localizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        internal static string FrmLogin_Esqueceu_senha {
            get {
                return ResourceManager.GetString("FrmLogin_Esqueceu_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password is invalid.
        /// </summary>
        internal static string FrmLogin_Falha_login {
            get {
                return ResourceManager.GetString("FrmLogin_Falha_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string FrmLogin_Iniciar_sessao {
            get {
                return ResourceManager.GetString("FrmLogin_Iniciar_sessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me connected.
        /// </summary>
        internal static string FrmLogin_Manter_conectado {
            get {
                return ResourceManager.GetString("FrmLogin_Manter_conectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string FrmLogin_Senha {
            get {
                return ResourceManager.GetString("FrmLogin_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check if the SQL Server service is running..
        /// </summary>
        internal static string FrmLogin_Servico_sql_parado {
            get {
                return ResourceManager.GetString("FrmLogin_Servico_sql_parado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string FrmLogin_Termina_sessao {
            get {
                return ResourceManager.GetString("FrmLogin_Termina_sessao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string FrmLogin_Usuario {
            get {
                return ResourceManager.GetString("FrmLogin_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user is no longer active.
        /// </summary>
        internal static string FrmLogin_Usuario_desativado {
            get {
                return ResourceManager.GetString("FrmLogin_Usuario_desativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string FrmMain_Ajuda {
            get {
                return ResourceManager.GetString("FrmMain_Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edgecam Manager help.
        /// </summary>
        internal static string FrmMain_AjudaEcMgr {
            get {
                return ResourceManager.GetString("FrmMain_AjudaEcMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job exporter.
        /// </summary>
        internal static string FrmMain_ExportaTrabalhos {
            get {
                return ResourceManager.GetString("FrmMain_ExportaTrabalhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string FrmMain_Ferramentas {
            get {
                return ResourceManager.GetString("FrmMain_Ferramentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop floor.
        /// </summary>
        internal static string FrmMain_GestoFabrica {
            get {
                return ResourceManager.GetString("FrmMain_GestoFabrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooling manager.
        /// </summary>
        internal static string FrmMain_GestorFerramentas {
            get {
                return ResourceManager.GetString("FrmMain_GestorFerramentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine manager.
        /// </summary>
        internal static string FrmMain_GestorMaquinas {
            get {
                return ResourceManager.GetString("FrmMain_GestorMaquinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job manager.
        /// </summary>
        internal static string FrmMain_GestorTrabalhos {
            get {
                return ResourceManager.GetString("FrmMain_GestorTrabalhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string FrmMain_Logoff {
            get {
                return ResourceManager.GetString("FrmMain_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FrmMain_MenuArq {
            get {
                return ResourceManager.GetString("FrmMain_MenuArq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string FrmMain_MenuInicio {
            get {
                return ResourceManager.GetString("FrmMain_MenuInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My data.
        /// </summary>
        internal static string FrmMain_MeusDados {
            get {
                return ResourceManager.GetString("FrmMain_MeusDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNCs files.
        /// </summary>
        internal static string FrmMain_NcEditor {
            get {
                return ResourceManager.GetString("FrmMain_NcEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string FrmMain_Opcoes {
            get {
                return ResourceManager.GetString("FrmMain_Opcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production orders.
        /// </summary>
        internal static string FrmMain_Ordens {
            get {
                return ResourceManager.GetString("FrmMain_Ordens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production tracking.
        /// </summary>
        internal static string FrmMain_RastrearVendas {
            get {
                return ResourceManager.GetString("FrmMain_RastrearVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string FrmMain_Relatorios {
            get {
                return ResourceManager.GetString("FrmMain_Relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FrmMain_Sair {
            get {
                return ResourceManager.GetString("FrmMain_Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Edgecam Manager.
        /// </summary>
        internal static string FrmMain_SobreEcMgr {
            get {
                return ResourceManager.GetString("FrmMain_SobreEcMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string FrmMain_TrocarSenha {
            get {
                return ResourceManager.GetString("FrmMain_TrocarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates.
        /// </summary>
        internal static string FrmMain_VerificarAtualizacoes {
            get {
                return ResourceManager.GetString("FrmMain_VerificarAtualizacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string FrmOrdem_ColunaAmbiente {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string FrmOrdem_ColunaArtigo {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaArtigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string FrmOrdem_ColunaCliente {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date.
        /// </summary>
        internal static string FrmOrdem_ColunaDataEntrega {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaDataEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required date.
        /// </summary>
        internal static string FrmOrdem_ColunaDataRequerida {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaDataRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string FrmOrdem_ColunaEstado {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation State.
        /// </summary>
        internal static string FrmOrdem_ColunaEstadoOperacao {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaEstadoOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string FrmOrdem_ColunaMaterial {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work center.
        /// </summary>
        internal static string FrmOrdem_ColunaMqn {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaMqn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Order.
        /// </summary>
        internal static string FrmOrdem_ColunaOrdem {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaOrdem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made.
        /// </summary>
        internal static string FrmOrdem_ColunaQtdeRealizada {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaQtdeRealizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string FrmOrdem_ColunaQtdeSolicitada {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaQtdeSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string FrmOrdem_ColunaTrabalho {
            get {
                return ResourceManager.GetString("FrmOrdem_ColunaTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open a connection to SQL.
        /// </summary>
        internal static string FrmUserConfigCnns_CnnNotOk {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_CnnNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established successfully.
        /// </summary>
        internal static string FrmUserConfigCnns_CnnOk {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_CnnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string FrmUserConfigCnns_Concluido {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Concluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a valid data.
        /// </summary>
        internal static string FrmUserConfigCnns_DadoValido {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_DadoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edgecam database.
        /// </summary>
        internal static string FrmUserConfigCnns_EcDb {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_EcDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password.
        /// </summary>
        internal static string FrmUserConfigCnns_EcPs {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_EcPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edgecam server.
        /// </summary>
        internal static string FrmUserConfigCnns_EcSrv {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_EcSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User for connection.
        /// </summary>
        internal static string FrmUserConfigCnns_EcUs {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_EcUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to create a new configuration file.
        /// </summary>
        internal static string FrmUserConfigCnns_ErroCriarCfg {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_ErroCriarCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields were not properly completed.
        /// </summary>
        internal static string FrmUserConfigCnns_ErroSalvarCfg {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_ErroSalvarCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server of the Edgecam Manager.
        /// </summary>
        internal static string FrmUserConfigCnns_Gp_Ax {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Gp_Ax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server of the Edgecam.
        /// </summary>
        internal static string FrmUserConfigCnns_Gp_Ec {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Gp_Ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edgecam Manager database.
        /// </summary>
        internal static string FrmUserConfigCnns_MgDb {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_MgDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edgecam Manager server.
        /// </summary>
        internal static string FrmUserConfigCnns_MgSrv {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_MgSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FrmUserConfigCnns_NaoConcluido {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_NaoConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string FrmUserConfigCnns_Return {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations was saved successfully.
        /// </summary>
        internal static string FrmUserConfigCnns_SalvouCfg {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_SalvouCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FrmUserConfigCnns_Save {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string FrmUserConfigCnns_TestCnn {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_TestCnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration.
        /// </summary>
        internal static string FrmUserConfigCnns_Title {
            get {
                return ResourceManager.GetString("FrmUserConfigCnns_Title", resourceCulture);
            }
        }
    }
}
