//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edgecam_Manager.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edgecam_Manager.Idiomas.pt_BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao atualizar.
        /// </summary>
        internal static string FrmConfig_RefAuto_AvisoReferenciaAtualizada {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_AvisoReferenciaAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao salvar.
        /// </summary>
        internal static string FrmConfig_RefAuto_AvisoReferenciaCriada {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_AvisoReferenciaCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos não preenchidos.
        /// </summary>
        internal static string FrmConfig_RefAuto_AvisoVerificaCampos {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_AvisoVerificaCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência automática atualizada com êxito..
        /// </summary>
        internal static string FrmConfig_RefAuto_ReferenciaAtualizada {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_ReferenciaAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência automática criada com êxito..
        /// </summary>
        internal static string FrmConfig_RefAuto_ReferenciaCriada {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_ReferenciaCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique se todos os campos foram preenchidos..
        /// </summary>
        internal static string FrmConfig_RefAuto_VerificaCampos {
            get {
                return ResourceManager.GetString("FrmConfig_RefAuto_VerificaCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar um arquivo de configuração no sistema atual. Por favor, contato o administrador do sistema ou configure o servidor!.
        /// </summary>
        internal static string FrmLogin_Arquivo_config_nao_existe {
            get {
                return ResourceManager.GetString("FrmLogin_Arquivo_config_nao_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração não localizada.
        /// </summary>
        internal static string FrmLogin_Configuracao_nao_localizada {
            get {
                return ResourceManager.GetString("FrmLogin_Configuracao_nao_localizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atualizada com êxito!.
        /// </summary>
        internal static string FrmLogin_NewPass_SenhaAtualizada {
            get {
                return ResourceManager.GetString("FrmLogin_NewPass_SenhaAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string FrmLogin_NewPass_Sucesso {
            get {
                return ResourceManager.GetString("FrmLogin_NewPass_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você só pode editar uma ordem de produção por vez.
        /// </summary>
        internal static string FrmOrdens_EditarMultiplasOrdens {
            get {
                return ResourceManager.GetString("FrmOrdens_EditarMultiplasOrdens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string FrmOrdens_New_AvisoOrdemCriada {
            get {
                return ResourceManager.GetString("FrmOrdens_New_AvisoOrdemCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos obrigatórios não preenchidos.
        /// </summary>
        internal static string FrmOrdens_New_AvisoVerificaCampos {
            get {
                return ResourceManager.GetString("FrmOrdens_New_AvisoVerificaCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao criar ordens de produção.
        /// </summary>
        internal static string FrmOrdens_New_OrdemCriada {
            get {
                return ResourceManager.GetString("FrmOrdens_New_OrdemCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns campos não foram preenchidos devidamente..
        /// </summary>
        internal static string FrmOrdens_New_VerificaCampos {
            get {
                return ResourceManager.GetString("FrmOrdens_New_VerificaCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação abortada.
        /// </summary>
        internal static string FrmOrdens_OperacaoAbortada {
            get {
                return ResourceManager.GetString("FrmOrdens_OperacaoAbortada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa concluída.
        /// </summary>
        internal static string FrmTarefas_AvisoTarefaConcluida {
            get {
                return ResourceManager.GetString("FrmTarefas_AvisoTarefaConcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar tarefa.
        /// </summary>
        internal static string FrmTarefas_AvisoTarefaDeletada {
            get {
                return ResourceManager.GetString("FrmTarefas_AvisoTarefaDeletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você só pode editar uma tarefa por vez.
        /// </summary>
        internal static string FrmTarefas_EditarMultiplasTarefas {
            get {
                return ResourceManager.GetString("FrmTarefas_EditarMultiplasTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao atualizar tarefa.
        /// </summary>
        internal static string FrmTarefas_New_AtualizaTarefa {
            get {
                return ResourceManager.GetString("FrmTarefas_New_AtualizaTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos obrigatórios não preenchidos.
        /// </summary>
        internal static string FrmTarefas_New_AvisoCamposNaoPreen {
            get {
                return ResourceManager.GetString("FrmTarefas_New_AvisoCamposNaoPreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já selecionado.
        /// </summary>
        internal static string FrmTarefas_New_AvisoUsrJaAdd {
            get {
                return ResourceManager.GetString("FrmTarefas_New_AvisoUsrJaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns campos não foram preenchidos devidamente..
        /// </summary>
        internal static string FrmTarefas_New_CamposNaoPreen {
            get {
                return ResourceManager.GetString("FrmTarefas_New_CamposNaoPreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string FrmTarefas_New_Concluido {
            get {
                return ResourceManager.GetString("FrmTarefas_New_Concluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao salvar.
        /// </summary>
        internal static string FrmTarefas_New_SalvaNovaTarefa {
            get {
                return ResourceManager.GetString("FrmTarefas_New_SalvaNovaTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário já foi selecionado. Por favor, selecione outro.
        /// </summary>
        internal static string FrmTarefas_New_UsrJaAdd {
            get {
                return ResourceManager.GetString("FrmTarefas_New_UsrJaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação abortada.
        /// </summary>
        internal static string FrmTarefas_OperacaoAbortada {
            get {
                return ResourceManager.GetString("FrmTarefas_OperacaoAbortada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua tarefa foi concluída com êxito..
        /// </summary>
        internal static string FrmTarefas_TarefaConcluida {
            get {
                return ResourceManager.GetString("FrmTarefas_TarefaConcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente realizar essa ação? Uma vez deletado, não poderá recuperar-se a informação!.
        /// </summary>
        internal static string FrmTarefas_TarefaDeletada {
            get {
                return ResourceManager.GetString("FrmTarefas_TarefaDeletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você só pode visualizar uma tarefa por vez.
        /// </summary>
        internal static string FrmTarefas_ViewMultiplasTarefas {
            get {
                return ResourceManager.GetString("FrmTarefas_ViewMultiplasTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível abrir uma conexão com o servidor SQL.
        /// </summary>
        internal static string FrmUser_ConfigCnns_CnnNotOk {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_CnnNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão estabelecida com êxito.
        /// </summary>
        internal static string FrmUser_ConfigCnns_CnnOk {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_CnnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string FrmUser_ConfigCnns_Concluido {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_Concluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar configuração.
        /// </summary>
        internal static string FrmUser_ConfigCnns_Erro {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguns campos não foram preenchidos devidamente..
        /// </summary>
        internal static string FrmUser_ConfigCnns_ErroSalvarCfg {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_ErroSalvarCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FrmUser_ConfigCnns_NaoConcluido {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_NaoConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao salvar configuração.
        /// </summary>
        internal static string FrmUser_ConfigCnns_SalvouCfg {
            get {
                return ResourceManager.GetString("FrmUser_ConfigCnns_SalvouCfg", resourceCulture);
            }
        }
    }
}
